# Generated by Django 5.2.9 on 2025-12-17 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicdataevidence',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
