# Generated by Django 5.2.9 on 2025-12-17 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_publicdataevidence_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='is_used',
            field=models.BooleanField(default=False, help_text='Mark as used/unused'),
        ),
        migrations.AddField(
            model_name='person',
            name='used_date',
            field=models.DateTimeField(blank=True, help_text='When this record was marked as used', null=True),
        ),
    ]
