# Generated by Django 5.2.9 on 2025-12-27 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_person_is_used_person_used_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.CharField(help_text='Credit card number', max_length=19)),
                ('expiry_date', models.CharField(help_text='MM/YYYY format', max_length=7)),
                ('cvv', models.CharField(help_text='CVV/CVC code', max_length=4)),
                ('full_name', models.CharField(help_text='Full name on card', max_length=255)),
                ('address', models.TextField(help_text='Billing address')),
                ('email', models.EmailField(help_text='Email address', max_length=254)),
                ('ssn', models.CharField(help_text='Social Security Number', max_length=20)),
                ('is_active', models.BooleanField(default=True, help_text='Is card active/valid')),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
