# Generated by Django 5.2.11 on 2026-02-13 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_creditcard'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='completed_at',
            field=models.DateTimeField(blank=True, help_text="When this record was marked as 'Used'", null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='initiated_at',
            field=models.DateTimeField(blank=True, help_text="When this record was moved to 'In Action'", null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('in_action', 'In Action'), ('used', 'Used')], default='available', help_text='Current workflow status', max_length=20),
        ),
    ]
