# Generated by Django 5.2.11 on 2026-02-13 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_person_completed_at_person_initiated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='research_notes',
            field=models.TextField(blank=True, help_text='Additional notes and information from research', null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='completed_at',
            field=models.DateTimeField(blank=True, help_text='When status changed to used', null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='initiated_at',
            field=models.DateTimeField(blank=True, help_text='When status changed to in_action', null=True),
        ),
    ]
